### ISSUE TITLE
zend_error_noreturn

### ISSUE THREAD

**Issue by toannguyen** [chobie/php-protocolbuffers#10]
Env: Linux  2.6.32-279.el6.i686 #1 SMP Fri Jun 22 10:59:55 UTC 2012 i686 i686 i386 GNU/Linux
Problem: PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/protocolbuffers.so' - /usr/lib/php/modules/protocolbuffers.so: undefined symbol: zend_error_noreturn in Unknown on line 0
Solved: change "zend_error_noreturn " to "zend_error"

**Comment by chobie** [comment]
hmm, could you copy `php -v` output here? probably I missed some includes.
I'll setup redhat VM and check it after back home.

**Comment by toannguyen** [comment]
PHP 5.5.0RC3 (cli) (built: Jun 14 2013 09:50:26)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.5.0-dev, Copyright (c) 1998-2013 Zend Technologies

**Comment by chobie** [comment]
@toannguyen  thanks, I'll check it later.

**Comment by chobie** [comment]
I looked into this problem with centos 6.2 but it doesn't reproduce it.
you know `zend_error_noreturn` is just alias for `zend_error`. so I use `zend_error` at this time.

Thanks,
