### ISSUE TITLE
please help me.thanks

### ISSUE THREAD

**Issue by dofounds** [chobie/php-protocolbuffers#11]
so:
<?php
require "addressbook.proto.php";
$db = "addressbook.db";
$handle = fopen($db, "r");
$data = fread($handle, filesize ($db));
$person = new Tutorial_AddressBook ();
$data = $person->parseFromString($data);

//$tm = $person->getDescriptor();

//echo $tm->getName();
print_r($data);

exit;

how to get the "$data"  information. and use the class functions

**Comment by chobie** [comment]
Hi, `parseFromString` is static method. so we should use it like this.

``` php
<?php
require "php/addressbook.proto.php";
$db = "addressbook.db";
$handle = fopen($db, "r");
// $data is raw protocol buffers binary data. 
$data = fread($handle, filesize ($db));

// you can decode it with `ProtocolBuffers::decode("Tutorial_AddressBook", $data);`
$addressbook = ProtocolBuffers::decode("Tutorial_AddressBook", $data);
// or you can use $addressbook = Tutorial_AddressBook::parseFromString($data);
foreach ($addressbook->getPerson() as $person) {
  var_dump($person);
}
```

Thanks,

**Comment by dofounds** [comment]
Thank you very much.
