### ISSUE TITLE
conver the protocolbuffer object to array problem

### ISSUE THREAD

**Issue by ryanchi** [chobie/php-protocolbuffers#14]
hello,chobie

as example the proto file design like this.
enum perm {
ALL = 0;
SYSTEM = 1;
ARTICLE = 2;
PIC = 3;
}

message Admin {
required string name = 1;
required string password = 2;
repeate perm purview = 3;
}

now,i write a function like this

function object_to_array($protobufobj){
        $fields  = $protobufobj->getDescriptor()->getFields();
        $arr = array();
        foreach($fields as $val) {
            $keyname = $val->getName();
            $arr[$keyname] = $protobufobj->get($keyname);
        }
        return $arr
    }

so when i got a  Admin object , i pass it to the object_to_array function ，i hope to get an array ，which the key of array is the property name ，and the value of the array is the value we set the property.

but when i run ，i got an segment fault error and some  stack information.  

i want to know whether i use the protocolbuffers extension error or the extension exist some problem.

thank you very much.

**Comment by chobie** [comment]
Hi, ryanchi.

> but when i run ，i got an segment fault error and some stack information.

I couldn't reproduce SEGV when I run OSX and ubuntu 12.04(64bit). 
Can you paste `uname -a` outputs and more specifically information?

Well, You can simply use `foreach` to iterate protobuf message.

``` php
<?php
require "admin.proto.php";

$admin = new Admin(array(
        "name" => "chobie",
        "password" => "**********",
        "preview" => array(1),
));

function object_to_array(\ProtocolBuffersMessage $message)
{
    $result = array();
    foreach ($message as $key => $value) {
         if ($value instanceof \ProtocolBuffersMessage) {
             $result[$key] = object_to_array($message);
         } else {
             $result[$key] = $value;
         }
    }

    return $result;
}

var_dump(object_to_array($admin));
```

this function outputs like this.

```
array(3) {
  ["name"]=>
  string(6) "chobie"
  ["password"]=>
  string(10) "**********"
  ["preview"]=>
  array(1) {
    [0]=>
    int(1)
  }
}
```

**Comment by ryanchi** [comment]
hello,chobie
Thank you for your answers carefully.

I'm sorry , I will  paste more information  tomorrow. thanks.

**Comment by chobie** [comment]
@ryanchi Hi, how about this?

**Comment by ryanchi** [comment]
hi chobie:

the uname -a result as follow:

Linux localhost.localdomain 2.6.32358.e16.x8664  #1 SMP Fri Feb 22 00:21:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

but i am not sure whether it is my software install problem.

**Comment by chobie** [comment]
thank you.

perhaps refcounting problem? It's easy to fix this problem If i can reproduce it.
for now, I'l keep this issue as open.

**Comment by chobie** [comment]
now, you can use toArray() method.
