### ISSUE TITLE
the int64 decode problem

### ISSUE THREAD

**Issue by X8888** [chobie/php-protocolbuffers#15]
hi chobie:

i found antohter problem,maybe there is a bug in the protocolbuffers extension;

i the a proto named time.proto ,its content is

message Time {
    uint64 start;
    uint64 end; 
}

then , i write a php.

<?php
require_once('time.proto.php');

$objin = new Time();
$start = time();
$end = $start+86400;
$objin->setStart($start _1000);
$objin->setEnd($end_1000);

var_dump($objin);
$bin = $objin->serializeToString();

$objout = ProtocolBuffers::decode('Time', $bin);
var_dump($objout);

?>

In theory, the value of the $objin and $objout  is the same. but
they are not .

the $objin is present correctly，maybe ，the value of  property start and end of $objout  present error ，maybe ，there is a numerical overflow。

i use the centos  operate system（ sixty-four - bit）.

best regards.

**Comment by chobie** [comment]
Hi, I'll check this issue when I back home. 
Thanks reporting it.

**Comment by X8888** [comment]
ok , the code above  i use microseconds．　Multiplied by 1000 ，like this.
$objin->setStart($start \* 1000);
$objin->setEnd($end *　1000);

**Comment by chobie** [comment]
@X8888 ah, sorry, I've missed about reading TYPE_VARINT value. 
Could you pull current master and check the behavior?

**Comment by X8888** [comment]
hi ,now i can get the right result .thank you.

root@ubuntu:~# /usr/local/php/bin/php ./a.php 
object(Time)#1 (2) {
  ["start":protected]=>
  int(1383921982000)
  ["end":protected]=>
  int(1384008382000)
}
object(Time)#2 (2) {
  ["start":protected]=>
  int(1383921982000)
  ["end":protected]=>
  int(1384008382000)
}

**Comment by X8888** [comment]
hi,i want to consulting a question with you.

the person.proto
message A {
    required string name = 1;
    required uint32 age = 2;
}

message A_List {
    repeated A person=1;
    required int32 max=2[default=0];
}

when i want to delete an repeated item,i just do so as follow:

<?php

require_once("person.proto.php");
$list = new A_List();
for($i =1 ;$i<=5; $i++) {

```
$p = new A();
$p->setName('a'.$i);
$p->setAge($i*3);

$list->appendPerson($p);
$list->setMax($i);
```

}

var_dump($list);

/**
- now i want to delete the person whose name is a2
  */

$person = $list->getPerson();

foreach($person as $key => $val) {
    if($val->getName() === 'a2') {
        unset($person[$key]);
    }
}

$list->clearPerson();
foreach($person as $key => $val) {
    $list->appendPerson($val);
}

var_dump($list);

so ,i delete the person whose name is a2,but  i think maybe this kind of writing is not optimal. do you have any better  ways to achieve the same effect.

thank you very much

**Comment by chobie** [comment]
Basically, protobuf doesn't provide API which arbitrarily remove an element from within a repeated field.
You should define a helper method on other class and use it.

```
class A_Helper
{
    public function DeleteByName($message, $name)
    {
       $person = $message->getPerson();
       foreach ($person as $offset => $p) {
            if ($person->getName() == $name) {
              unset($person[$offset]);
            }
       }
       $message->setPerson($person);
    }
}
```

But, PHP really poor like this operation. so I should add some helper method for this kind of it.

ref: http://stackoverflow.com/questions/13603878/how-to-delete-arbitrary-objects-in-repeated-field-protobuf

**Comment by X8888** [comment]
hi:

in the A_Helper class ,the  $message->getPerson() get an array(), so it is an repeated property. why use setPerson method ( the protocolbuffer extension does not contain the set{Property} method)?

ah,when i want to delete or modify an repeated property item ,i found there is no suitable api calls.

maybe,It's a good idea to increase these api interface.

thank you
