### ISSUE TITLE
how can i delete item with repeated field

### ISSUE THREAD

**Issue by muyilangjun** [chobie/php-protocolbuffers#17]
demo:
message A {
required int32 item =1;
}

how can i delete a item ?

I got a idea ,add a function

```
/**
 * 删掉一个数据
 * @param $index
 */
public function removeItem($index) {
    array_splice($this->item, $index, 1);
}
```

can you add this feature

**Comment by chobie** [comment]
Hi, please check this thread. 

https://github.com/chobie/php-protocolbuffers/issues/15

Maybe I'll add helper method for easy to remove it

**Comment by muyilangjun** [comment]
ok,thanks
