### ISSUE TITLE
OS X (10.9) build error (unexpected type name 'pb_globals': expected expression)

### ISSUE THREAD

**Issue by cypres** [chobie/php-protocolbuffers#18]
Got a "protocol_buffers.c:257:112: error: unexpected type name 'pb_globals': expected expression" error when compiling with clan on OS X.

 cc -I. -I/Users/hans/Sites/php-protocolbuffers -DPHP_ATOM_INC -I/Users/hans/Sites/php-protocolbuffers/include -I/Users/hans/Sites/php-protocolbuffers/main -I/Users/hans/Sites/php-protocolbuffers -I/usr/local/Cellar/php54/5.4.20/include/php -I/usr/local/Cellar/php54/5.4.20/include/php/main -I/usr/local/Cellar/php54/5.4.20/include/php/TSRM -I/usr/local/Cellar/php54/5.4.20/include/php/Zend -I/usr/local/Cellar/php54/5.4.20/include/php/ext -I/usr/local/Cellar/php54/5.4.20/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /Users/hans/Sites/php-protocolbuffers/protocol_buffers.c  -fno-common -DPIC -o .libs/protocol_buffers.o

```
/Users/hans/Sites/php-protocolbuffers/protocol_buffers.c:257:112: error: unexpected type name 'pb_globals': expected expression
  STD_PHP_INI_BOOLEAN("protocolbuffers.strict_mode", "1", PHP_INI_ALL, OnUpdateLong, strict_mode, pb_globals,   pb_globals)
                                                                                                                ^
/usr/local/Cellar/php54/5.4.20/include/php/Zend/zend_ini.h:154:124: note: expanded from macro 'STD_ZEND_INI_BOOLEAN'
        ZEND_INI_ENTRY3_EX(name, default_value, modifiable, on_modify, (void *) XtOffsetOf(struct_type, property_name), (void *) &struct_ptr, NULL, zend_ini_boolean_displayer_cb)
                                                                                                                                  ^
/usr/local/Cellar/php54/5.4.20/include/php/Zend/zend_ini.h:118:56: note: expanded from macro 'ZEND_INI_ENTRY3_EX'
        { 0, modifiable, name, sizeof(name), on_modify, arg1, arg2, arg3, default_value, sizeof(default_value)-1, NULL, 0, 0, 0, displayer },
                                                              ^
1 error generated.
```

**Comment by chobie** [comment]
ah, sorry. I forget to check with non-zts PHP. fixed it.
