### ISSUE TITLE
Error After installation

### ISSUE THREAD

**Issue by chetanch** [chobie/php-protocolbuffers#20]
We have installed this proto buff but while generating class from proto, we are getting below Error
--php_out: protoc-gen-php: Plugin killed by signal 11.
Please reply asap

**Comment by chobie** [comment]
@chetanch Hi, What kind of system do you use? please paste `uname -a` result.

and, could you show me .proto file which cause segmentation fault?

**Comment by chetanch** [comment]
Thanks for your valuable response. I am using below system and proto file  https://developers.google.com/ad-exchange/rtb/downloads/realtime-bidding-proto.txt, Please save this  as .proto and use that
Red Hat Enterprise Linux Server release 6.2 (Santiago)
After executing below command, 
  protoc --plugin=contrib/protoc-gen-php examples/realtime-bidding.proto --php_out=examples/php -I . -I /usr/local/include
We are getting below error
--php_out: protoc-gen-php: Plugin killed by signal 11.

**Comment by chobie** [comment]
just fixed SEGV.

Currently, php-protocolbuffers is under experimental status. please evaluate carefully and don't rely my implementation. I wrote some test cases but It may contains bug.

I'll check my implementation with google rtb.

**Comment by chobie** [comment]
for your information: I've just played rtb with this https://github.com/chobie/php-rtb-server

I found some improvements when I played it. i'll improve my ext.
