### ISSUE TITLE
VC9 build problems

### ISSUE THREAD

**Issue by MonkeyMaster** [chobie/php-protocolbuffers#22]
I finally managed to build this extension as a dll with Visual Studio 2008.
I used official manual to prepare the environment: https://wiki.php.net/internals/windows/stepbystepbuild

I had three issues (the first two even in static build mode):
- <code>kMaxVarintBytes</code> & <code>kMaxVarint32Bytes</code> are not recongized, compilation error at helper.h:143. I replaced them with values.
- Functions <code>strtoull</code> & <code>atoll</code> are missing - I added to helper.h:

``` c
#define strtoull _strtoui64
#define atoll _atoi64
```
- Unresolved external symbol <code>__imp__php_pb_globals_id</code> when linker builds a dll. I removed <code>PHPAPI</code> at protocol_buffers.c:47

Please consider fixing them.

**Comment by chobie** [comment]
Thanks reporting the issue. I've just fixed compile errors. also fixes globals.

Honestly, I wonder this ext works on windows box. please make sure yourself at this time.
I'll support windows platform foreseeable future. But now, I'd like to improve other things at first (e.g protoc-gen-php, internal implementations...). 
sometimes I might broke windows build untill construct windows jenkins server.

Anyway, reporting and patches are welcome :octocat:

**Comment by MonkeyMaster** [comment]
Thank you, the new version builds as dll fine
