### ISSUE TITLE
Suggestion: batch setting of message fields

### ISSUE THREAD

**Issue by MonkeyMaster** [chobie/php-protocolbuffers#25]
In addition to current implementation of setting fields one at a time

``` php
$message = new Diadoc_Api_Proto_Events_MessageToPost;
$message->setIsDraft(true);
$message->setStrictDraftValidation(false);
$message->setFromBoxId('id1');
$message->setToBoxId('id2');
$message->serializeToString();
```

it would be nice to have an ability to set all fields at once this way:

``` php
$message = new Diadoc_Api_Proto_Events_MessageToPost(array(
  'IsDraft' => true,
  'StrictDraftValidation' => false,
  'FromBoxId' => 'id1',
  'ToBoxId' => 'id2',
));
```

or this:

``` php
$message = new Diadoc_Api_Proto_Events_MessageToPost;
$message->set(array(
  'IsDraft' => true,
  'StrictDraftValidation' => false,
  'FromBoxId' => 'id1',
  'ToBoxId' => 'id2',
));
```

**Comment by chobie** [comment]
`ProtocolBuffers\Message::__construct` accepts array parameter. maybe It'll work.
current set method is `ProtocolBuffers\Message::set($property_name, $value)`.

yea, Sometimes want do batch set. I'll consider api signature.

**Comment by chobie** [comment]
I've added  `ProtocolBuffers::setFrom(array $values)` for batch set operation like this.

```
$message = new Diadoc_Api_Proto_Events_MessageToPost;
$message->setFrom(array(
  'IsDraft' => true,
  'StrictDraftValidation' => false,
  'FromBoxId' => 'id1',
  'ToBoxId' => 'id2',
));
```

**Comment by MonkeyMaster** [comment]
great, thanks!
now it works both ways:

``` php
$message = new Diadoc_Api_Proto_Events_MessageToPost(['isdraft' => true]);
$message->setFrom(['isdraft' => true]);
echo $message->getIsDraft();
```

Just investigated that all methods expect field names in lower case even if proto-file has camel case.

**Comment by chobie** [comment]
hmm, `__construct` and `setFrom` methods expected same case string as proto file. I'll fix this.

**Comment by MonkeyMaster** [comment]
<code>get</code>, <code>set</code>, <code>has</code> methods also require lower-cased names

**Comment by MonkeyMaster** [comment]
it works, thanks!
