### ISSUE TITLE
Segfault at parseFromString

### ISSUE THREAD

**Issue by dcelasun** [chobie/php-protocolbuffers#31]
This is a very weird issue but I can't debug it myself as I don't have a debug build of PHP.

Here are the proto files in question:

File `clientConfigFile.proto`:

```
package wom2.protobuf.messages;

option java_outer_classname = "ClientConfigFileProto";

message ClientConfigFile
{
    required string name = 1;
    optional string value = 2;
    optional int32 version = 3;
}
```

File `webAuthMessage.proto`:

```
package wom2.protobuf.messages;

option java_outer_classname = "WebAuthMessageProto";

import "clientConfigFile.proto";

message WebAuthMessage
{
    required int64 id = 1;
    required int32 pid = 2;
    optional int64 fbid = 3;
    optional string gcid = 4;
    optional string gpid = 5;
    optional string ios_ifv = 6;
    optional string and_id = 7;
    repeated ClientConfigFile configVersions = 8;
}
```

Here's a simple `test.php` file that can reproduce the crash:

```
<?php
require "../vendor/autoload.php";
use wom2\protobuf\messages\WebAuthMessage;

$s = 'CA4QAUIVChF2aXN1YWxjb25maWcuanNvbhgBQhMKD2RvbWFpbmluZm8uanNvbhgC';
$input = base64_decode($s, true);

WebAuthMessage::parseFromString($input);
```

`$input` contains a valid `WebAuthMessage`. Now, trying to execute this, I get the following:

```
$ php test.php 
Segmentation fault (core dumped)
```

I'm using PHP 5.5.8 on Linux x86-64.

Any ideas?

**Comment by dcelasun** [comment]
Here's an even simpler example that uses this compiler to generate the message:

```
<?php
require "../vendor/autoload.php";
use wom2\protobuf\messages\WebAuthMessage;

$msg = new WebAuthMessage();

$msg->setId(123);
$msg->setPid(1);

$cf = new \wom2\protobuf\messages\ClientConfigFile();

$cf->setName("foo");
$cf->setVersion(12);

$msg->appendConfigVersions($cf);

$str = $msg->serializeToString();

$parsed = WebAuthMessage::parseFromString($str);

echo "<pre>";var_dump($parsed);exit;
```

This script also fails with a segfault.

**Comment by chobie** [comment]
Thanks reporting an issue. I've fixed this problem.

I Usually uses lower case field name so I didn't notice this problem.

**Comment by dcelasun** [comment]
Wow thanks! We were doing some final tests before using this in production and the quick fix is appreciated.

Now the only remaining issue seems to be #32.

**Comment by chobie** [comment]
oops, travis build seems failed. but it's just 5.2 related issue please don't mind it at this time.
let me look into #32.
