### ISSUE TITLE
The message contains a message data that has been serialized

### ISSUE THREAD

**Issue by b40yd** [chobie/php-protocolbuffers#37]
message Hello {
    required string type = 1;
    required string data = 2;
}

message world {
    required string name  = 1;
    required int32 year  = 2;
}

php code:

$h = new Hello();
$w = new world();

$h->setType("world");

$w->setName("earth");
$w->setYear(2014);

$h->setData($w->serializeToString());

$h->serializeToString();

error: this string ,it not is vaild utf-8

**Comment by chobie** [comment]
hmm. I couldn't reproduce this issue. 

```
 PHP Fatal error:  Uncaught exception 'ProtocolBuffersInvalidByteSequenceException' with message 'passed string is not valid utf8 string' in /Users/chobie/src/issue37/issue.php:14
Stack trace:
#0 /Users/chobie/src/issue37/issue.php(14): ProtocolBuffersMessage->serializeToString()
#1 {main}
  thrown in /Users/chobie/src/issue37/issue.php on line 14
```

Could you paste  `php -r 'var_dump(ini_get("protocolbuffers.validate_string"));'` output?
utf8 validation will ignore when that value returns 0.

**Comment by dcelasun** [comment]
If you want to pass a serialized message to another message, the field type should be `bytes`, not `string`, i.e:

```
message Hello {
required string type = 1;
optional bytes data = 2;
}
```

This way, `$h->setData($w->serializeToString())` will work fine. We actually use this extensively at work.

**Comment by chobie** [comment]
thanks @dcelasun 

probably I misunderstood the context. I hope this document will be helpful to you.
https://developers.google.com/protocol-buffers/docs/proto#scalar

string type must contains utf8 encoded or 7-bit ascii text. so please use bytes type instead of it.

**Comment by b40yd** [comment]
@dcelasun @chobie 
thanks ,used bytes is working.
