### ISSUE TITLE
ProtocolBuffersMessage::__construct() is broken with repeated fields

### ISSUE THREAD

**Issue by dcelasun** [chobie/php-protocolbuffers#41]
Latest version (0.2.6) seems to be broken with:

> ProtocolBuffersMessage::__construct() expects parameter 1 to be array, object given

Sample proto:

```
message TestMessage
{
    repeated TestUser users = 1;
}

message TestUser
{
    required int64 id = 1;
}
```

Sample PHP:

```
$bar = new TestMessage(['users' => [
    new TestUser(['id' => 1])
]]);
```

Same problem also happens with `setFrom()` method.

**Comment by chobie** [comment]
for now I've fixed it. I'll more test cases when I back home.
