### ISSUE TITLE
ProtocolBuffersMessage::__construct() segfaults with invalid field names

### ISSUE THREAD

**Issue by dcelasun** [chobie/php-protocolbuffers#44]
This is a minor issue, but here it goes:

```
message TestMessage {
    optional string test = 1;
}
```

Test code:

```
$test = new TestMessage(["foo" => "bar"]);
```

This results in a segfault. Maybe it could throw an `InvalidArgumentException`?

**Comment by chobie** [comment]
thanks reporting issue. I'll check this when I back home.

**Comment by chobie** [comment]
I've checked with 747a2238f14de0be67d5747089b50ebcc5e1116c and v0.2.6 but couldn't reproduce.
What version did you used?

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'foo does not find' in /Users/chobie/src/php-protocolbuffers/44.php:4
Stack trace:
#0 /Users/chobie/src/php-protocolbuffers/44.php(4): ProtocolBuffersMessage->__construct(Array)
#1 {main}
  thrown in /Users/chobie/src/php-protocolbuffers/44.php on line 4
```

**Comment by chobie** [comment]
Oops, I haven't tested with linux box.

**Comment by dcelasun** [comment]
@chobie I did a bit more testing and this only seems to happen within a very specific case in my codebase; I cannot reproduce it in isolation. I'll try to get a debug PHP build and get a stack trace for you.

I'm closing this bug for now, I'll reopen it once I have more data.
