### ISSUE TITLE
PHP -> Java -> PHP -> ProtocolBuffersInvalidProtocolBufferException on parseFromString()

### ISSUE THREAD

**Issue by ghost** [chobie/php-protocolbuffers#47]
Sending to Java over activeMQ as bytes message works perfect on a Windows 7 64 machine using php-5.5.14-nts-Win32-VC11-x86 and PHP PB 0.2.6 alpha 2014-04-15 DLL from PECL.
Recieving the response from Java in PHP makes headaches. Proto file:

package net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc;
option java_package = "net.x3.service.adapter.jms.barcode.zxing.protobuf.rpc";
option java_outer_classname = "zebracrossing";
option optimize_for = SPEED;

message ZXingMultiFormatDecodeImageRequest {
    required bytes image = 1;
    optional int32 resolution_start = 2;
    optional int32 resolution_stop = 3;
    optional int32 short_side_step = 4;
}
message ZXingException {
    required string exception_type = 1;
    required string exception_message = 2;
    optional string stack_trace = 3 [default = ""];
}
message ZXingResponse {
    optional string result = 1;
    optional ZXingException exception = 2;
}

Short version of the Code:

$imageString = file_get_contents('images/test.png');
$request = new \net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc\ZXingMultiFormatDecodeImageRequest();
$request->setImage($imageString);
$request->setResolutionStart('16384');
$request->setResolutionStop('4194304');
$request->setShortSideStep('1');
$serialized = $request->serializeToString();
// until now everything works, java receives and parses the request succesfully and sends return
// get body from returned JMS message which is String, part of the correct return value is visible
$bytes = $msg->body;
$deserialized = \net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc\ZXingResponse::parseFromString(strval($bytes));

Exception on parseFromString()

PHP Fatal error:  Uncaught exception 'ProtocolBuffersInvalidProtocolBufferException' with message 'passed variable contains malformed byte sequence. or it contains unsupported tag' in C:\Users\x3.mbetzel\Development\workspaces\php\StompProtoBuf\zxing.php:59
Stack trace:
#0 C:\Users\x3.mbetzel\Development\workspaces\php\StompProtoBuf\zxing.php(59): ProtocolBuffersMessage::parseFromString('\xB3\x02HMM2000123456...')
#1 {main}

  thrown in C:\Users\x3.mbetzel\Development\workspaces\php\StompProtoBuf\zxing.php on line 59

The strange thing is that if i return this object from Java with an exception everything is good:

Received message
class net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc\ZXingResponse#9 (2) {
  protected $result =>
  string(0) ""
  protected $exception =>
  class net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc\ZXingException#8 (3) {
    protected $exception_type =>
    string(34) "java.lang.IllegalArgumentException"
    protected $exception_message =>
    string(16) "No barcode found"
    protected $stack_trace =>
    string(0) ""
  }
}

Any ideas?

**Comment by dcelasun** [comment]
```
 $deserialized = \net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc\ZXingResponse::parseFromString(strval($bytes));
```

Can you try it without `strval`?

**Comment by ghost** [comment]
Does not change a thing. As soon as i add a result string things go wrong. Protocolbuffers::decode and encode have the same results. Generated response code:
<?php
namespace net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc;
// @@protoc_insertion_point(namespace:.net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc.ZXingResponse)
/**
- Generated by the protocol buffer compiler.  DO NOT EDIT!
- source: tests/proto/zxingrpc.proto
  *
- -_\- magic methods -_-
  *
- @method string getResult()
- @method void setResult(\string $value)
- @method \net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc\ZXingException getException()
- @method void setException(\net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc\ZXingException $value)
  _/
  class ZXingResponse extends \ProtocolBuffers\Message
  {
  // @@protoc_insertion_point(traits:.net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc.ZXingResponse)
  /_*
  - @var string $result
  - @tag 1
  - @label optional
  - @type \ProtocolBuffers::TYPE_STRING
    **/
    protected $result;
    /**
  - @var \net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc\ZXingException $exception
  - @tag 2
  - @label optional
  - @type \ProtocolBuffers::TYPE_MESSAGE
    **/
    protected $exception;
    // @@protoc_insertion_point(properties_scope:.net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc.ZXingResponse)
    // @@protoc_insertion_point(class_scope:.net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc.ZXingResponse)
    /**
  - get descriptor for protocol buffers
  - 
  - @return \ProtocolBuffersDescriptor
    */
    public static function getDescriptor()
    {
    static $descriptor;
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "result",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "exception",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc\ZXingException',
      )));
      // @@protoc_insertion_point(builder_scope:.net_x3_service_adapter_jms_barcode_zxing_protobuf_rpc.ZXingResponse)
      $descriptor = $desc->build();
    }
    return $descriptor;
    }
    }

**Comment by ghost** [comment]
I have found the problem and it has to do with the fuse source implementation 1.x of STOMP.
When executing readFrame(), it truncated the bytes by doing a trim on the message body removing all whitespace. The solution is the following new function for Stomp.php, whatch this line only stripping "\x00" instead of all whitespace :

$frame = new StompFrame($command, $headers, trim($body, "\x00"));

 /**
     \* Read response frame from server for binairy messages
     *
     \* @return StompFrame False when no frame to read
     */
    public function readFrameBinairy ()
    {
        if (!$this->hasFrameToRead()) {
            return false;
        }

```
    $rb = 1024;
    $data = '';
    $end = false;

    do {
        $read = fread($this->_socket, $rb);
        if ($read === false) {
            $this->_reconnect();
            return $this->readFrame();
        }
        $data .= $read;
        if (strpos($data, "\x00") !== false) {
            $end = true;
            $data = rtrim($data, "\n");
        }
        $len = strlen($data);
    } while ($len < 2 || $end == false);

    list ($header, $body) = explode("\n\n", $data, 2);
    $header = explode("\n", $header);
    $headers = array();
    $command = null;
    foreach ($header as $v) {
        if (isset($command)) {
            list ($name, $value) = explode(':', $v, 2);
            $headers[$name] = $value;
        } else {
            $command = $v;
        }
    }
    $frame = new StompFrame($command, $headers, trim($body, "\x00"));
    if (isset($frame->headers['transformation']) && $frame->headers['transformation'] == 'jms-map-json') {
        require_once 'Stomp/Map.php';
        return new StompMessageMap($frame);
    } else {
        return $frame;
    }
    return $frame;
}
```

Thanks to my colleague Jan Grävell  for his excelent PHP knowlledge.
