### ISSUE TITLE
Installing php-protocolbuffers fails at composer step

### ISSUE THREAD

**Issue by rob-watts** [chobie/php-protocolbuffers#55]
Hello,

I'm following the setup instructions on ubuntu 14.04 with 5.5.9

When I get to the setup where, in my home directory, where I downloaded php-protocolbuffers.git & protoc-gen-php.git I get this error when I try to run:

composer install 

test@server2:/var/www/test/protoc-gen-php$ sudo composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-protocolbuffers \* is missing from your system. Install or enable PHP's protocolbuffers extension.

The phpinfo() function says protocol buffers 0.2.5 is installed but php -m on the command line doesn't show the loaded module.

I think this is the issue but I don't know how to resolve this.  

Can you tell me where I went wrong?

**Comment by dcelasun** [comment]
PHP extensions are not installed with Composer. To compile/install it, follow [these](https://github.com/chobie/php-protocolbuffers#install) steps and restart PHP. After that, Composer should detect the extension.

**Comment by rob-watts** [comment]
Thank you.  I ended up going with the Allegro library which I was able to get working.
