### ISSUE TITLE
case sensitive field

### ISSUE THREAD

**Issue by toannguyen** [chobie/php-protocolbuffers#8]
When dec field, "regPlace" 
Err:  undefined method ::setRegPlace()

**Comment by chobie** [comment]
Yea, current imlementation expects snake case field name.
I'll add an option for accept this case.

Thanks

**Comment by chobie** [comment]
for now, support case sensitive fields. but I should ask google guys about how to treat case sensitive fields.

**Comment by chobie** [comment]
okay, we should use underscore_separated_names for member name.
https://developers.google.com/protocol-buffers/docs/style

Technically, magic method is able to detect case sensitive field name. but user land method does not.
so I recommend to follow google's style when you define a message.

``` php
<?php

class A extends ProtocolBuffers\Message
{
  public function getBar()
  {
  }

  // you can't define `getbar` method as already defined above.
  public function getbar()
  {
  }
}

# Fatal error: Cannot redeclare A::getbar() in check.php on line 9
```
